################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../m2tklib/m2.c \
../m2tklib/m2align.c \
../m2tklib/m2dfs.c \
../m2tklib/m2draw.c \
../m2tklib/m2eh2bs.c \
../m2tklib/m2elalign.c \
../m2tklib/m2elfnfmt.c \
../m2tklib/m2ellabel.c \
../m2tklib/m2ellistbase.c \
../m2tklib/m2ellistcalc.c \
../m2tklib/m2ellisth.c \
../m2tklib/m2ellistv.c \
../m2tklib/m2elroot.c \
../m2tklib/m2elsb.c \
../m2tklib/m2elslbase.c \
../m2tklib/m2elstr.c \
../m2tklib/m2elsubutl.c \
../m2tklib/m2elu32.c \
../m2tklib/m2elxbm.c \
../m2tklib/m2esarmu8g.c \
../m2tklib/m2fnarg.c \
../m2tklib/m2gfx.c \
../m2tklib/m2gfxutl.c \
../m2tklib/m2ghdummy.c \
../m2tklib/m2ghu8gbfs.c \
../m2tklib/m2ghu8gicon.c \
../m2tklib/m2ghu8gutl.c \
../m2tklib/m2key.c \
../m2tklib/m2navdatadn.c \
../m2tklib/m2navdataup.c \
../m2tklib/m2navfirst.c \
../m2tklib/m2navinit.c \
../m2tklib/m2navnext.c \
../m2tklib/m2navroot.c \
../m2tklib/m2navupdn.c \
../m2tklib/m2navutl.c \
../m2tklib/m2null.c \
../m2tklib/m2obj.c \
../m2tklib/m2opt.c \
../m2tklib/m2pin.c \
../m2tklib/m2rom.c \
../m2tklib/m2usrnext.c \
../m2tklib/m2usrupdn.c 

OBJS += \
./m2tklib/m2.obj \
./m2tklib/m2align.obj \
./m2tklib/m2dfs.obj \
./m2tklib/m2draw.obj \
./m2tklib/m2eh2bs.obj \
./m2tklib/m2elalign.obj \
./m2tklib/m2elfnfmt.obj \
./m2tklib/m2ellabel.obj \
./m2tklib/m2ellistbase.obj \
./m2tklib/m2ellistcalc.obj \
./m2tklib/m2ellisth.obj \
./m2tklib/m2ellistv.obj \
./m2tklib/m2elroot.obj \
./m2tklib/m2elsb.obj \
./m2tklib/m2elslbase.obj \
./m2tklib/m2elstr.obj \
./m2tklib/m2elsubutl.obj \
./m2tklib/m2elu32.obj \
./m2tklib/m2elxbm.obj \
./m2tklib/m2esarmu8g.obj \
./m2tklib/m2fnarg.obj \
./m2tklib/m2gfx.obj \
./m2tklib/m2gfxutl.obj \
./m2tklib/m2ghdummy.obj \
./m2tklib/m2ghu8gbfs.obj \
./m2tklib/m2ghu8gicon.obj \
./m2tklib/m2ghu8gutl.obj \
./m2tklib/m2key.obj \
./m2tklib/m2navdatadn.obj \
./m2tklib/m2navdataup.obj \
./m2tklib/m2navfirst.obj \
./m2tklib/m2navinit.obj \
./m2tklib/m2navnext.obj \
./m2tklib/m2navroot.obj \
./m2tklib/m2navupdn.obj \
./m2tklib/m2navutl.obj \
./m2tklib/m2null.obj \
./m2tklib/m2obj.obj \
./m2tklib/m2opt.obj \
./m2tklib/m2pin.obj \
./m2tklib/m2rom.obj \
./m2tklib/m2usrnext.obj \
./m2tklib/m2usrupdn.obj 

C_DEPS += \
./m2tklib/m2.pp \
./m2tklib/m2align.pp \
./m2tklib/m2dfs.pp \
./m2tklib/m2draw.pp \
./m2tklib/m2eh2bs.pp \
./m2tklib/m2elalign.pp \
./m2tklib/m2elfnfmt.pp \
./m2tklib/m2ellabel.pp \
./m2tklib/m2ellistbase.pp \
./m2tklib/m2ellistcalc.pp \
./m2tklib/m2ellisth.pp \
./m2tklib/m2ellistv.pp \
./m2tklib/m2elroot.pp \
./m2tklib/m2elsb.pp \
./m2tklib/m2elslbase.pp \
./m2tklib/m2elstr.pp \
./m2tklib/m2elsubutl.pp \
./m2tklib/m2elu32.pp \
./m2tklib/m2elxbm.pp \
./m2tklib/m2esarmu8g.pp \
./m2tklib/m2fnarg.pp \
./m2tklib/m2gfx.pp \
./m2tklib/m2gfxutl.pp \
./m2tklib/m2ghdummy.pp \
./m2tklib/m2ghu8gbfs.pp \
./m2tklib/m2ghu8gicon.pp \
./m2tklib/m2ghu8gutl.pp \
./m2tklib/m2key.pp \
./m2tklib/m2navdatadn.pp \
./m2tklib/m2navdataup.pp \
./m2tklib/m2navfirst.pp \
./m2tklib/m2navinit.pp \
./m2tklib/m2navnext.pp \
./m2tklib/m2navroot.pp \
./m2tklib/m2navupdn.pp \
./m2tklib/m2navutl.pp \
./m2tklib/m2null.pp \
./m2tklib/m2obj.pp \
./m2tklib/m2opt.pp \
./m2tklib/m2pin.pp \
./m2tklib/m2rom.pp \
./m2tklib/m2usrnext.pp \
./m2tklib/m2usrupdn.pp 

C_DEPS__QUOTED += \
"m2tklib\m2.pp" \
"m2tklib\m2align.pp" \
"m2tklib\m2dfs.pp" \
"m2tklib\m2draw.pp" \
"m2tklib\m2eh2bs.pp" \
"m2tklib\m2elalign.pp" \
"m2tklib\m2elfnfmt.pp" \
"m2tklib\m2ellabel.pp" \
"m2tklib\m2ellistbase.pp" \
"m2tklib\m2ellistcalc.pp" \
"m2tklib\m2ellisth.pp" \
"m2tklib\m2ellistv.pp" \
"m2tklib\m2elroot.pp" \
"m2tklib\m2elsb.pp" \
"m2tklib\m2elslbase.pp" \
"m2tklib\m2elstr.pp" \
"m2tklib\m2elsubutl.pp" \
"m2tklib\m2elu32.pp" \
"m2tklib\m2elxbm.pp" \
"m2tklib\m2esarmu8g.pp" \
"m2tklib\m2fnarg.pp" \
"m2tklib\m2gfx.pp" \
"m2tklib\m2gfxutl.pp" \
"m2tklib\m2ghdummy.pp" \
"m2tklib\m2ghu8gbfs.pp" \
"m2tklib\m2ghu8gicon.pp" \
"m2tklib\m2ghu8gutl.pp" \
"m2tklib\m2key.pp" \
"m2tklib\m2navdatadn.pp" \
"m2tklib\m2navdataup.pp" \
"m2tklib\m2navfirst.pp" \
"m2tklib\m2navinit.pp" \
"m2tklib\m2navnext.pp" \
"m2tklib\m2navroot.pp" \
"m2tklib\m2navupdn.pp" \
"m2tklib\m2navutl.pp" \
"m2tklib\m2null.pp" \
"m2tklib\m2obj.pp" \
"m2tklib\m2opt.pp" \
"m2tklib\m2pin.pp" \
"m2tklib\m2rom.pp" \
"m2tklib\m2usrnext.pp" \
"m2tklib\m2usrupdn.pp" 

OBJS__QUOTED += \
"m2tklib\m2.obj" \
"m2tklib\m2align.obj" \
"m2tklib\m2dfs.obj" \
"m2tklib\m2draw.obj" \
"m2tklib\m2eh2bs.obj" \
"m2tklib\m2elalign.obj" \
"m2tklib\m2elfnfmt.obj" \
"m2tklib\m2ellabel.obj" \
"m2tklib\m2ellistbase.obj" \
"m2tklib\m2ellistcalc.obj" \
"m2tklib\m2ellisth.obj" \
"m2tklib\m2ellistv.obj" \
"m2tklib\m2elroot.obj" \
"m2tklib\m2elsb.obj" \
"m2tklib\m2elslbase.obj" \
"m2tklib\m2elstr.obj" \
"m2tklib\m2elsubutl.obj" \
"m2tklib\m2elu32.obj" \
"m2tklib\m2elxbm.obj" \
"m2tklib\m2esarmu8g.obj" \
"m2tklib\m2fnarg.obj" \
"m2tklib\m2gfx.obj" \
"m2tklib\m2gfxutl.obj" \
"m2tklib\m2ghdummy.obj" \
"m2tklib\m2ghu8gbfs.obj" \
"m2tklib\m2ghu8gicon.obj" \
"m2tklib\m2ghu8gutl.obj" \
"m2tklib\m2key.obj" \
"m2tklib\m2navdatadn.obj" \
"m2tklib\m2navdataup.obj" \
"m2tklib\m2navfirst.obj" \
"m2tklib\m2navinit.obj" \
"m2tklib\m2navnext.obj" \
"m2tklib\m2navroot.obj" \
"m2tklib\m2navupdn.obj" \
"m2tklib\m2navutl.obj" \
"m2tklib\m2null.obj" \
"m2tklib\m2obj.obj" \
"m2tklib\m2opt.obj" \
"m2tklib\m2pin.obj" \
"m2tklib\m2rom.obj" \
"m2tklib\m2usrnext.obj" \
"m2tklib\m2usrupdn.obj" 

C_SRCS__QUOTED += \
"../m2tklib/m2.c" \
"../m2tklib/m2align.c" \
"../m2tklib/m2dfs.c" \
"../m2tklib/m2draw.c" \
"../m2tklib/m2eh2bs.c" \
"../m2tklib/m2elalign.c" \
"../m2tklib/m2elfnfmt.c" \
"../m2tklib/m2ellabel.c" \
"../m2tklib/m2ellistbase.c" \
"../m2tklib/m2ellistcalc.c" \
"../m2tklib/m2ellisth.c" \
"../m2tklib/m2ellistv.c" \
"../m2tklib/m2elroot.c" \
"../m2tklib/m2elsb.c" \
"../m2tklib/m2elslbase.c" \
"../m2tklib/m2elstr.c" \
"../m2tklib/m2elsubutl.c" \
"../m2tklib/m2elu32.c" \
"../m2tklib/m2elxbm.c" \
"../m2tklib/m2esarmu8g.c" \
"../m2tklib/m2fnarg.c" \
"../m2tklib/m2gfx.c" \
"../m2tklib/m2gfxutl.c" \
"../m2tklib/m2ghdummy.c" \
"../m2tklib/m2ghu8gbfs.c" \
"../m2tklib/m2ghu8gicon.c" \
"../m2tklib/m2ghu8gutl.c" \
"../m2tklib/m2key.c" \
"../m2tklib/m2navdatadn.c" \
"../m2tklib/m2navdataup.c" \
"../m2tklib/m2navfirst.c" \
"../m2tklib/m2navinit.c" \
"../m2tklib/m2navnext.c" \
"../m2tklib/m2navroot.c" \
"../m2tklib/m2navupdn.c" \
"../m2tklib/m2navutl.c" \
"../m2tklib/m2null.c" \
"../m2tklib/m2obj.c" \
"../m2tklib/m2opt.c" \
"../m2tklib/m2pin.c" \
"../m2tklib/m2rom.c" \
"../m2tklib/m2usrnext.c" \
"../m2tklib/m2usrupdn.c" 


